apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "mgp-timings"
    version: "${project.version}"
    group: "fabricepipart"
  name: "mgp-timings"
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: "mgp-timings"
    version: "${project.version}"
    group: "fabricepipart"
  type: "ClusterIP"